# Use Node.js 18 as the base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy everything to the container
COPY . .

# Install dependencies and build frontend
RUN echo "Installing dependencies and building frontend..." && \
    cd frontend && \
    npm install && \
    npm run build:skip-ts && \
    cd ../server && \
    npm install --only=production

# Expose port
EXPOSE 5001

# Set working directory to server
WORKDIR /app/server

# Start server
CMD ["node", "server.js"]
