[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 5

[nixpacks]
nodejs-version = "18"

[variables]
NODE_ENV = "production"
PORT = "5001"
